-- COUNTRY
INSERT INTO COUNTRY (MAJOR_AREA, REGION, COUNTRY) VALUES ('Latin America and the Caribbean','Central America','Mexico');
INSERT INTO COUNTRY (MAJOR_AREA, REGION, COUNTRY) VALUES ('Europe','Southern Europe','Spain');
INSERT INTO COUNTRY (MAJOR_AREA, REGION, COUNTRY) VALUES ('Asia','Eastern Asia','Japan');
INSERT INTO COUNTRY (MAJOR_AREA, REGION, COUNTRY) VALUES ('Asia','Eastern Asia','China');
INSERT INTO COUNTRY (MAJOR_AREA, REGION, COUNTRY) VALUES ('Asia','South-eastern Asia','Thailand');

-- GENE
INSERT INTO GENE (GENE_NAME) VALUES ('OXER1');
INSERT INTO GENE (GENE_NAME) VALUES ('TBX3');
INSERT INTO GENE (GENE_NAME) VALUES ('PPM1F');

-- REGION
INSERT INTO REGION (NAME) VALUES ('13q14.11');

-- SNP
INSERT INTO SINGLE_NUCLEOTIDE_POLYMORPHISM (RS_ID, CHROMOSOME_NAME, CHROMOSOME_POSITION, LAST_UPDATE_DATE, REGION_ID) VALUES ('rs7329174', '19', '6546489897', TO_DATE('2010-05-27 14:27:19', 'yyyy-mm-dd HH24:MI:SS'), 1);

-- EFOTRAIT
INSERT INTO EFO_TRAIT (TRAIT, URI) VALUES ('systemic lupus erythematosus', 'http://www.ebi.ac.uk/efo/EFO_0002690');
INSERT INTO EFO_TRAIT (TRAIT, URI) VALUES ('acute lung injury', 'http://www.ebi.ac.uk/efo/EFO_0004610');

-- CURATOR
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES ('Joannella','Morales', 'jmorales@ebi.ac.uk','moralesj2');
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES ('Jackie','MacArthur','jalm@ebi.ac.uk','macarthurja');
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES ('Lucia','Hindorff','hindorffl@mail.nih.gov','hindorffl');
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES ('Heather','Junkins','junkinsh@mail.nih.gov','junkinsh');
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES ('Peggy','Hall','Peggy.Hall@nih.gov','kwongp');
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES ('Dani','Welter','dwelter@ebi.ac.uk','welterd');
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES ('Shaila','Chhibba','shaila.chhibba@nih.gov','chhibbas');
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES ('Emily', 'Bowler', null, null);
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES (null, 'Unassigned', null, null);
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES (null, 'GWAS Catalog', null, null);
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES (null, 'Level 2 Curator', null, null);
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES (null, 'Level 1 Curator', null, null);
INSERT INTO CURATOR (FIRST_NAME, LAST_NAME, EMAIL, USER_NAME) VALUES (null, 'Level 1 Ethnicity Curator', null, null);

-- CURATION_STATUS
INSERT INTO CURATION_STATUS (STATUS, SEQNBR) VALUES ('Awaiting Curation','0');
INSERT INTO CURATION_STATUS (STATUS, SEQNBR) VALUES ('Level 1 curation done','2');
INSERT INTO CURATION_STATUS (STATUS, SEQNBR) VALUES ('Level 2 curation done','4');
INSERT INTO CURATION_STATUS (STATUS, SEQNBR) VALUES ('Send to NCBI',	'5');
INSERT INTO CURATION_STATUS (STATUS, SEQNBR) VALUES ('Publish study','6');
INSERT INTO CURATION_STATUS (STATUS, SEQNBR) VALUES ('Outstanding Query','11');

-- DISEASE_TRAIT
INSERT INTO DISEASE_TRAIT (TRAIT) VALUES ('Systemic lupus erythematosus');
INSERT INTO DISEASE_TRAIT (TRAIT) VALUES ('Acute lung injury');

-- HOUSEKEEPING
INSERT INTO HOUSEKEEPING (STUDY_SNP_CHECKED_LEVEL_ONE, STUDY_SNP_CHECKED_LEVEL_TWO, PUBLISH_DATE, NOTES, ETHNICITY_CHECKED_LEVEL_ONE, ETHNICITY_CHECKED_LEVEL_TWO, SEND_TONCBIDATE, CHECKEDNCBIERROR, FILE_NAME, CURATOR_ID, CURATION_STATUS_ID, ETHNICITY_BACK_FILLED, STUDY_ADDED_DATE, LAST_UPDATE_DATE) VALUES ('1', '1', TO_DATE('2011-01-03 15:19:20', 'yyyy-mm-dd HH24:MI:SS'), 'Here are some notes about this study', '1', '1', NULL,'0','/nfs/gwas/Yang.21044949.2010.pdf', 1, 2,'1' , TO_DATE('2011-01-03 00:00:00', 'yyyy-mm-dd HH24:MI:SS'), TO_DATE('2014-06-09 08:17:40', 'yyyy-mm-dd HH24:MI:SS'));
INSERT INTO HOUSEKEEPING (STUDY_SNP_CHECKED_LEVEL_ONE, STUDY_SNP_CHECKED_LEVEL_TWO, PUBLISH_DATE, NOTES, ETHNICITY_CHECKED_LEVEL_ONE, ETHNICITY_CHECKED_LEVEL_TWO, SEND_TONCBIDATE, CHECKEDNCBIERROR, FILE_NAME, CURATOR_ID, CURATION_STATUS_ID, ETHNICITY_BACK_FILLED, STUDY_ADDED_DATE, LAST_UPDATE_DATE) VALUES ('1', '1', TO_DATE('2012-01-03 15:19:20', 'yyyy-mm-dd HH24:MI:SS'), 'No combine or meta-analysis result to report no significant Pvalue from any study, PH', '1', '1', NULL,'0','Christie.Acute lung injury.PLoS One.2012.pdf', 2, 3 ,'1' , TO_DATE('2011-01-03 00:00:00', 'yyyy-mm-dd HH24:MI:SS'), TO_DATE('2014-06-09 08:17:40', 'yyyy-mm-dd HH24:MI:SS'));

-- STUDY
INSERT INTO STUDY (AUTHOR, STUDY_DATE, PUBLICATION, TITLE, INITIAL_SAMPLE_SIZE, REPLICATE_SAMPLE_SIZE, PLATFORM, PUBMED_ID, CNV, GXE, GXG, HOUSEKEEPING_ID) VALUES ('Yang J', TO_DATE('2010-11-02 00:00:00', 'yyyy-mm-dd HH24:MI:SS'), 'Hum Mol Genet','ELF1 is associated with systemic lupus erythematosus in Asian populations','612 Chinese ancestry cases, 1,160 Chinese ancestry controls','2,090 Chinese ancestry cases, 1,981 Chinese ancestry controls, 462 Thai ancestry cases, 951 Thai ancestry controls','Illumina [513,108]', '21044949', '1', '0', '1', 1);
INSERT INTO STUDY (AUTHOR, STUDY_DATE, PUBLICATION, TITLE, INITIAL_SAMPLE_SIZE, REPLICATE_SAMPLE_SIZE, PLATFORM, PUBMED_ID, CNV, GXE, GXG, HOUSEKEEPING_ID) VALUES ('Christie JD', TO_DATE('2012-01-25 00:00:00', 'yyyy-mm-dd HH24:MI:SS'), 'PLoS Onet','Genome wide association identifies PPFIA1 as a candidate gene for acute lung injury risk following major trauma','600 European ancestry cases, 2,266 European ancestry controls','212 European ancestry cases, 283 European ancestry controls','Illumina [2,487,415] (imputed)', '22295056', '0', '0', '0', 2);

-- ETHNICITY
INSERT INTO ETHNICITY (STUDY_ID, TYPE, NUMBER_OF_INDIVIDUALS, ETHNIC_GROUP, COUNTRY_OF_ORIGIN, COUNTRY_OF_RECRUITMENT, DESCRIPTION, PREVIOUSLY_REPORTED, SAMPLE_SIZES_MATCH, NOTES) VALUES (1, 'replication', 1413, 'South East Asian', null, 'Thailand', 'Bangkok, Thailand', null, 'Y', null);
INSERT INTO ETHNICITY (STUDY_ID, TYPE, NUMBER_OF_INDIVIDUALS, ETHNIC_GROUP, COUNTRY_OF_ORIGIN, COUNTRY_OF_RECRUITMENT, DESCRIPTION, PREVIOUSLY_REPORTED, SAMPLE_SIZES_MATCH, NOTES) VALUES (1, 'initial', 1772, 'East Asian', null, 'China', 'Hefei, Anhui Province, China; Hong Kong, China;', null, 'Y', null);
INSERT INTO ETHNICITY (STUDY_ID, TYPE, NUMBER_OF_INDIVIDUALS, ETHNIC_GROUP, COUNTRY_OF_ORIGIN, COUNTRY_OF_RECRUITMENT, DESCRIPTION, PREVIOUSLY_REPORTED, SAMPLE_SIZES_MATCH, NOTES) VALUES (1, 'replication', 4071, 'East Asian', null, 'China', 'Anhui, China; Hong Kong, China;', null, 'Y', null);
INSERT INTO ETHNICITY (STUDY_ID, TYPE, NUMBER_OF_INDIVIDUALS, ETHNIC_GROUP, COUNTRY_OF_ORIGIN, COUNTRY_OF_RECRUITMENT, DESCRIPTION, PREVIOUSLY_REPORTED, SAMPLE_SIZES_MATCH, NOTES) VALUES (2, 'initial', 2566, 'European', null, 'U.S.', 'Cambridge, MA; Nashville, TN; Seattle, WA; San Francisco, CA; Philadelphia, PA', 'NR', 'Y', 'Sample size in table S1; description in methods');
INSERT INTO ETHNICITY (STUDY_ID, TYPE, NUMBER_OF_INDIVIDUALS, ETHNIC_GROUP, COUNTRY_OF_ORIGIN, COUNTRY_OF_RECRUITMENT, DESCRIPTION, PREVIOUSLY_REPORTED, SAMPLE_SIZES_MATCH, NOTES) VALUES (2, 'replication', 495, 'European', null, 'U.S.', 'Cambridge, MA; Philadelphia, PA; Nashville, TN; Seattle, WA; San Francisco, CA', 'NR', 'Y', 'Sample size in table S1; description in methods');

-- ASSOCIATION
INSERT INTO ASSOCIATION (STUDY_ID, SNP_ID, STRONGEST_ALLELE, RISK_FREQUENCY, ALLELE, PVALUE_FLOAT, PVALUE_TEXT, OR_PER_COPY_NUM, OR_TYPE, SNP_TYPE, PVALUE_MANTISSA, PVALUE_EXPONENT, OR_PER_COPY_RECIP, OR_PER_COPY_STD_ERROR, OR_PER_COPY_RANGE, OR_PER_COPY_UNIT_DESCR) VALUES (1, 1, 'rs7329174-G', '0.22', 'G', 1E-8, null, 1.26, '1','Novel', 1, -8, null, null,'[1.16-1.36]', null);
INSERT INTO ASSOCIATION (STUDY_ID, SNP_ID, STRONGEST_ALLELE, RISK_FREQUENCY, ALLELE, PVALUE_FLOAT, PVALUE_TEXT, OR_PER_COPY_NUM, OR_TYPE, SNP_TYPE, PVALUE_MANTISSA, PVALUE_EXPONENT, OR_PER_COPY_RECIP, OR_PER_COPY_STD_ERROR, OR_PER_COPY_RANGE, OR_PER_COPY_UNIT_DESCR) VALUES (2, 1, 'rs7329174-G', '0.22', 'G', 1E-8, null, 1.26, '1','Novel', 1, -8, null, null,'[1.16-1.36]', null);

-- SNP_GENE_SNP
INSERT INTO SNP_GENE (GENE_ID, SNP_ID) VALUES (1,1);
INSERT INTO SNP_GENE (GENE_ID, SNP_ID) VALUES (2,1);
INSERT INTO SNP_GENE (GENE_ID, SNP_ID) VALUES (3,1);

-- STUDY_SNP
INSERT INTO STUDY_SNP (STUDY_ID, SNP_ID) VALUES (1,1);
INSERT INTO STUDY_SNP (STUDY_ID, SNP_ID) VALUES (2,1);

-- STUDY_DISEASE_TRAIT
INSERT INTO STUDY_DISEASE_TRAIT (STUDY_ID, DISEASE_TRAIT_ID) VALUES(1, 1);
INSERT INTO STUDY_DISEASE_TRAIT (STUDY_ID, DISEASE_TRAIT_ID) VALUES(2, 2);
