-- COUNTRY
CREATE OR REPLACE TRIGGER COUNTRY_TRG BEFORE INSERT ON COUNTRY FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER COUNTRY_TRG ENABLE;

-- GENE
CREATE OR REPLACE TRIGGER GENE_TRG BEFORE INSERT ON GENE FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER GENE_TRG ENABLE;

-- REGION
CREATE OR REPLACE TRIGGER REGION_TRG BEFORE INSERT ON REGION FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER REGION_TRG ENABLE;

-- SNP
CREATE OR REPLACE TRIGGER SNP_TRG BEFORE INSERT ON SINGLE_NUCLEOTIDE_POLYMORPHISM FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER SNP_TRG ENABLE;

-- EFOTRAIT
CREATE OR REPLACE TRIGGER EFO_TRAIT_TRG BEFORE INSERT ON EFO_TRAIT FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER EFO_TRAIT_TRG ENABLE;

-- CURATOR
CREATE OR REPLACE TRIGGER CURATOR_TRG BEFORE INSERT ON CURATOR FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER CURATOR_TRG ENABLE;

-- CURATION_STATUS
CREATE OR REPLACE TRIGGER CURATION_STATUS_TRG BEFORE INSERT ON CURATION_STATUS FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER CURATION_STATUS_TRG ENABLE;

-- DISEASE_TRAIT
CREATE OR REPLACE TRIGGER DISEASE_TRAIT_TRG BEFORE INSERT ON DISEASE_TRAIT FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER DISEASE_TRAIT_TRG ENABLE;

-- HOUSEKEEPING
CREATE OR REPLACE TRIGGER HOUSEKEEPING_TRG BEFORE INSERT ON HOUSEKEEPING FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER HOUSEKEEPING_TRG ENABLE;

-- STUDY
CREATE OR REPLACE TRIGGER STUDY_TRG BEFORE INSERT ON STUDY FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER STUDY_TRG ENABLE;

-- ETHNICITY
CREATE OR REPLACE TRIGGER ETHNICITY_TRG BEFORE INSERT ON ETHNICITY FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER ETHNICITY_TRG ENABLE;

-- ASSOCIATION
CREATE OR REPLACE TRIGGER ASSOCIATION_TRG BEFORE INSERT ON ASSOCIATION FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END; ;
ALTER TRIGGER ASSOCIATION_TRG ENABLE;
