language: java
sudo: false
jdk:
- openjdk8

env:
  global:
  - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx512M"
addons:
  sonarcloud:
    organization: "gwas-ebi"
    #token:
      #secure: "LBTAViqGyi7anEYYLzuTyTF1L3Xnq7prupvyzW2mIUWJY6uh9Y3s0TItA+8CSUcbeCUf6MGrj8ydNi4PRLr/DpOCTIrt4FMs5mljaBE4BDfJMgts/hSzLSwSLOa2gKdOJg64ZNpeW+am/hH5/Wbuje6cegeNoNq1yRH4SMBLhnu3/JdmzDLc3pLNuhvNjy6/qX2YPyHLoJ9FE0SfkbULsbzHy7+EDLcxPUVby7aemOD0KUYDxw7Ee4jc5mH9HDrm9sqTFHw+4TWNMA5gsZX4NB3keSElMg9giwVTQT3zLG2sFNbhmhoD2rxs7JxTE+yVeg7ahLSW23LP7mkg4jdc4gR4h1VxB6wwxHIsx+1QZP8MSBOcwYPzLQIp3VyGK37sCVDJHGrpQXZG9SHWZfedmqo6EjabZK8lFCGG8fOTIj5A5FiltfaaHvEfgwbMki12zTm8GftodPJNUT336FNvTHOUlG/RNP3exArWpLXXZXw1gynn57tEVdd5qxdxxpc+QztJiKn2dByWehg5NYh7KwkGcQiNAerYYzMDpIjaVKO1hHeCSouuYFXxp++gBPW0z68Eojp7bVORA/I82nZdY6lkEnFFryHo3RTgU8q6ggDI233r10R/Unsl4bySisQ6z1McPZERQMIton1XMqbAkh3Eb337L+GEGzRSlLehNGM="
script:
- mvn clean verify sonar:sonar -Dmaven.test.failure.ignore=true -Dmaven.test.error.ignore=true -Dsonar.login=0566d66d0cfe16cd2cb8ba02db7fcd0b6d1e7ee6
