= About the GWAS Catalog

== About the GWAS Catalog

The Catalog was founded by the https://www.genome.gov[NHGRI] in 2008, in response to the rapid increase in the number of published genome-wide association studies (GWAS). These studies provide an unprecedented opportunity to investigate the impact of common variants on complex disease; however identifying published GWAS can be challenging, and the vast wealth of data contained within these publications is effectively inaccessible to researchers without systematic cataloguing and summarization of the observed associations. The GWAS Catalog provides a consistent, searchable, visualisable and freely available database of published SNP-trait associations, which can be easily integrated with other resources, and is accessed by scientists, clinicians and other users worldwide.
Within the Catalog, all link:methods[eligible] GWA studies are identified by literature search and assessed by our curators, who then extract the reported trait, significant SNP-trait associations, and sample metadata. We aim to curate eligible studies within 1-2 months of publication, dependent on the availability of literature, and the data is released on a weekly cycle. The Catalog also publishes the iconic https://www.ebi.ac.uk/gwas/diagram[GWAS diagram] of SNP-trait associations, mapped onto the human genome by chromosomal location and displayed on the human karyotype.
Since 2010, delivery and development of the Catalog has been a collaborative project between the EMBL-EBI and NHGRI. The Catalog website and infrastructure is now hosted by EMBL-EBI. A team of curators, all of whom are experienced molecular biologists, curate the data, and provide user support. The curation team is supported by dedicated software developers, and is lead by Fiona Cunningham, Paul Flicek & Helen Parkinson, and Lucia Hindorff at the NHGRI. We work closely with the https://www.ebi.ac.uk/about/people/helen-parkinson[SPOT] and http://www.ensembl.org/info/about/index.html[Ensembl] teams at the EBI, and receive input from an independent Scientific Advisory Board.
For more details about the Catalog curation process and data extraction procedures, please refer to the link:methods[Methods page].

== Contact

=== Contacting the GWAS Catalog team

To contact the GWAS Catalog team, with queries, comments, feedback or to add your summary statistics to the GWAS Catalog, please email gwas-info@ebi.ac.uk. Please see our link:faq[FAQ page] for answers to some common queries about the GWAS Catalog. For more help using the GWAS Catalog, please have a look at our link:related-resources[training resources].


=== Keeping up-to-date

We announce new releases and other developments on our announcement list, \gwas-announce@ebi.ac.uk. link:++mailto:gwas-announce-join@ebi.ac.uk?subject=subscribe&body=Please subscribe me to receive GWAS Catalog updates++[Sign up for updates]. 

To interact with other GWAS Catalog users, join our user community mailing list, \gwas-users@ebi.ac.uk. link:++mailto:gwas-users-join@ebi.ac.uk?subject=subscribe&body=Please subscribe me to the GWAS users list++[Send us a quick email] to subscribe to this list. 

You can also follow us on Twitter https://twitter.com/GWASCatalog[@GWASCatalog].


== Funding acknowledgements

The NHGRI-EBI GWAS Catalog is funded by NHGRI Grant Number 2U41HG007823, and delivered by collaboration between the NHGRI, EMBL-EBI and NCBI.


== Citing the GWAS Catalog


=== How to cite the NHGRI-EBI GWAS Catalog or data therein:

_MacArthur J, Bowler E, Cerezo M, Gil L, Hall P, Hastings E, Junkins H, McMahon A, Milano  A, Morales J, Pendlington Z, Welter D, Burdett T, Hindorff L, Flicek P, Cunningham F, and Parkinson H._ +
The new NHGRI-EBI Catalog of published genome-wide association studies (GWAS Catalog). +
Nucleic Acids Research, 2017, Vol. 45 (Database issue): D896-D901. +

For a full list of publications by the GWAS Catalog team, and other useful background reading, please visit our link:related-resources[Resources page]


== Licensing information

The NHGRI-EBI GWAS Catalog and all its contents are available under the general http://www.ebi.ac.uk/about/terms-of-use[Terms of Use for EMBL-EBI Services].

All code for the GWAS Catalog infrastructure can be found in https://github.com/EBISPOT/goci[our Github repository]. The code is freely available under http://www.apache.org/licenses/LICENSE-2.0[the Apache version 2.0 license]



== Credits &amp; acknowledgements

* Font generated by http://www.flaticon.com[flaticon.com] under http://creativecommons.org/licenses/by/3.0/[CC BY license].
The authors are http://picol.org[Picol].

* http://www.jetbrains.com/idea/index.html[IntelliJ IDEA]: Full-featured commercial IDE with a complete set of tools and integrations with the most important modern technologies and frameworks, such as Spring and Hibernate — a must-have for effective Web and Java EE development.

