= About the GWAS Catalog

== About the GWAS Catalog

The GWAS Catalog is provided jointly by the http://www.genome.gov[National Human Genome Research Institute (NHGRI)] and the http://www.ebi.ac.uk[European Bioinformatics Institute (EMBL-EBI)]. The Catalog was founded by the NHGRI in 2008, with delivery and development of the Catalog being a collaborative project between the EMBL-EBI and NHGRI from September 2010 to the present. In March 2015 the Catalog infrastructure moved to EMBL-EBI to enable delivery of an improved user interface and curatorial infrastructure, funded by http://projectreporter.nih.gov/project_info_description.cfm?aid=8739756&icde=23818978[NHGRI Grant Number 1U41HG007823-01].

The Catalog is a quality controlled, manually curated, literature-derived collection of all published http://en.wikipedia.org/wiki/Genome-wide_association_study[genome-wide association studies] assaying at least 100,000 http://en.wikipedia.org/wiki/Single-nucleotide_polymorphism[SNPs] and all SNP-trait associations with p-values < 1.0 x 10^-5^ _(Hindorff et al., 2009)_. For more details about the Catalog curation process and data extraction procedures, please refer to the link:methods[Methods page].

The Catalog also publishes the iconic GWAS diagram of all SNP-trait associations, with p-values &le; 5.0 x 10^-8^, mapped onto the human genome by chromosomal locations and displayed on the human karyotype. The diagram is released nightly and the latest version of the http://www.ebi.ac.uk/gwas/diagram[diagram] is made available on our website in SVG format.


== Funding acknowledgements

The NHGRI-EBI GWAS Catalog is funded in part by http://projectreporter.nih.gov/project_info_description.cfm?aid=8739756&icde=23818978[NHGRI Grant Number 1U41HG007823-01] and BBSRC Grant Number BB/M013146/1, and delivered by collaboration between the NHGRI, EMBL-EBI and NCBI.


== Citing the GWAS Catalog

===  How to cite NHGRI-EBI GWAS Catalog data:

_Burdett T (EBI), Hall PN (NHGRI), Hastings E (EBI), Hindorff LA (NHGRI), Junkins HA (NHGRI), Klemm AK (NHGRI), MacArthur J (EBI), Manolio TA (NHGRI), Morales J (EBI), Parkinson H (EBI) and Welter D (EBI)._ +
The NHGRI-EBI Catalog of published genome-wide association studies. +
Available at: www.ebi.ac.uk/gwas. Accessed [date of access], version [version number]. +
_version number only applies to the download spreadsheet - v1.0 for the traditional version of the spreadsheet, v1.0.1 for the version with added EFO terms_  +

=== How to cite the NHGRI-EBI GWAS Catalog:

_Welter D, MacArthur J, Morales J, Burdett T, Hall P, Junkins H, Klemm A, Flicek P, Manolio T, Hindorff L, and Parkinson H._ +
The NHGRI GWAS Catalog, a curated resource of SNP-trait associations. +
Nucleic Acids Research, 2014, Vol. 42 (Database issue): D1001-D1006. +


== Licensing information

The NHGRI-EBI GWAS Catalog and all its contents are available under the general http://www.ebi.ac.uk/about/terms-of-use[Terms of Use for EMBL-EBI Services].

All code for the GWAS Catalog infrastructure can be found in https://github.com/EBISPOT/goci[our Github repository]. The code is freely available under http://www.apache.org/licenses/LICENSE-2.0[the Apache version 2.0 license]


== Publications

_Welter D, MacArthur J, Morales J, Burdett T, Hall P, Junkins H, Klemm A, Flicek P, Manolio T, Hindorff L, and Parkinson H._ +
http://nar.oxfordjournals.org/content/42/D1/D1001.full[The NHGRI GWAS Catalog, a curated resource of SNP-trait associations.] +
Nucleic Acids Research, 2014, Vol. 42 (Database issue): D1001-D1006. +

_Hindorff LA, Sethupathy P, Junkins HA, Ramos EM, Mehta JP, Collins FS and Manolio TA._ +
http://www.genome.gov/Pages/About/OD/NewsAndFeatures/PNASGWASOnlineCatalog.pdf[Potential etiologic and functional implications of genome-wide association loci for human diseases and traits.] +
Proc. Natl Acad. Sci. USA, 2009, 106, 9362–9367 +



== Contact

=== Contacting the GWAS Catalog team

To contact the GWAS Catalog team, please email gwas-info@ebi.ac.uk. Please see our link:faq[FAQ page] for some common queries about the GWAS Catalog in general and the new search portal in particular.


=== Keeping up-to-date with new releases and developments

We announce new releases and other developments on our announcement list, \gwas-announce@ebi.ac.uk. link:++mailto:gwas-announce-join@ebi.ac.uk?subject=subscribe&body=Please subscribe me to receive GWAS Catalog updates++[Sign up for updates].


=== User community

To interact with other GWAS Catalog users, join our user community mailing list, \gwas-users@ebi.ac.uk. link:++mailto:gwas-users-join@ebi.ac.uk?subject=subscribe&body=Please subscribe me to the GWAS users list++[Send us a quick email] to subscribe to this list. You can also follow us on Twitter https://twitter.com/GWASCatalog[@GWASCatalog].



== Credits &amp; acknowledgements

* Font generated by http://www.flaticon.com[flaticon.com] under http://creativecommons.org/licenses/by/3.0/[CC BY license].
The authors are http://picol.org[Picol].

* http://www.jetbrains.com/idea/index.html[IntelliJ IDEA]: Full-featured commercial IDE with a complete set of tools and integrations with the most important modern technologies and frameworks, such as Spring and Hibernate — a must-have for effective Web and Java EE development.

