= Ancestry

== Ancestry data
Sample ancestry information is available in two distinct forms; a free text sample description and structured ancestry and recruitment information. The free text descriptions of the initial and replication stages of the GWAS provide summary ancestry descriptions of the samples analysed in each stage, based on the language used in the paper. The structured information is designed to represent data using controlled terms, enabling searching, visualisation and integration. It includes ancestry, chosen from a list of 15 ancestral categories, and country of recruitment.

Country of recruitment is extracted if an author states the country of recruitment of the samples. The country of recruitment is not assumed from an ancestry identifier or from a cohort name. Where a country of recruitment but no ancestry is provided, published population demographic information, such as the https://www.cia.gov/library/publications/the-world-factbook/[CIA World Factbook], is consulted.

Sample ancestry and country of recruitment information is searchable, available through the expanded “Studies” table and as a download from link:fileheaders[ our download page]. For an overview of the kind of data found in this file, refer to link:fileheaders#_file_headers_for_ancestry_download[ the file header descriptions].


=== References
The following publications include analysis of the GWAS Catalog ancestry data.

_Popejoy AB and Fullerton SM._ +
http://www.nature.com/news/genomics-is-failing-on-diversity-1.20759[Genomics is failing on diversity] +
Nature. 2016, 538 (7624), 161-164. +

_Need, AC and Goldstein, DB._ +
http://europepmc.org/abstract/MED/19836853[Next generation disparities in human genomics: concerns and remedies] +
Trends Genet. 2009, 25, 489–494. +

