= Ancestry documentation

== Ancestry Framework

Essential to the interpretation of GWAS data is the accurate description of the ancestry of samples included in these studies. The GWAS Catalog team has link:https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1396-2[developed and published a framework] to represent, in an accurate and standardized manner, the ancestry of samples. Our framework involves representing the ancestry of samples in two forms: (1) a detailed sample description and (2) an ancestry category from a controlled list. Detailed descriptions aim to capture accurate, informative, and comprehensive information regarding the ancestry or genealogy of each distinct sample. Category assignment reduces complexity within data sets and enables the establishment of hierarchical relationships, placing samples in context with other samples, groups, and populations. 

Following a detailed review of ancestry information in the GWAS Catalog, we have also made some link:ancestry-recommendation[recommendations to authors].

== Curation Process

Each GWAS Catalog study entry comprises one or more samples, designated as “Initial” or “Replication” samples, depending on the stage of the GWA study in which they were analysed. For each sample, we created the detailed description by extracting the ancestry descriptor utilized by the author in the relevant publication. To generate the controlled description, we selected, from a limited list of terms, the category noted by the author or, if not stated, the category that best correlates with the detailed description for the same sample. For example, we selected the category “East Asian” for detailed descriptions containing the descriptor “Han Chinese”. 

We rely heavily on data stated by authors in the GWAS publication, giving precedence to information inferred using genomic methods, such as principal component analysis (PCA). In some cases, we considered other sources, but only when the information provided by authors was limited or ambiguous. We consulted peer-reviewed population genetics publications to obtain additional information on lesser-known groups that were not adequately characterized by authors or when samples were described using ethno-cultural terms.

When the only information provided in the curated publication was the location of recruitment, we consulted link:https://unstats.un.org/unsd/methodology/m49[The United Nations M49 Standard of Geographic Regions] and link:https://www.cia.gov/library/publications/resources/the-world-factbook/index.html[The World Factbook]. The latter is a regularly updated compendium of worldwide demographic data, covering all countries and territories of the world. 

We also extract country information as it  provides additional detail on sample demographics. 

== Description of Methods

=== Detailed Sample Description

* Detailed descriptions for the initial and replication stages of the GWAS are entered separately as “Initial Sample Description” and “Replication Sample Description”.  
* Catalog detailed descriptions include the most detailed ancestry descriptor provided by the author, e.g. “Han Chinese”, “Black”, “Jewish”, “Thai”, “Colored African”.
* Samples described in a publication as “White” or “Caucasian” are described in the detailed description as European.
* If multiple populations of the same ancestry category are included in a study, the samples are combined by ancestry category. For example, for a study that includes 100 Japanese ancestry individuals and 200 Korean ancestry individuals, the detailed description states "300 East Asian ancestry individuals". When multiple sample populations are combined in this way the descriptions provided by the author for each sample population are included in the “Additional information” field in the structured ancestry data.
* It is assumed that a descriptor, e.g. “Dutch”, refers to ancestry and not citizenship or country of recruitment unless information is provided to contradict this. For example, if the author states “100 Dutch cases”, European ancestry is inferred, rather than recruitment in The Netherlands.
* A founder population or genetic isolate has genetic homogeneity or limited genetic variation within the population. Each founder/genetic isolate descriptor is decided on a case by case basis, using the authors’ language and description of the sample from the paper being curated, followed by the term “founder/genetic isolate”. For example, the Sardinian population isolate from Sardinia, Italy is listed as “Sardinian (founder/genetic isolate)”. 
* Populations with ancestry from more than one distinct parental population are considered to be admixed. Currently, the vast majority of Catalog samples with recent admixture can be categorized as “African American or Afro-Caribbean” or “Hispanic or Latin American”. When describing samples with recent admixture distinct from these populations, the detailed descriptor is decided on a case by case basis, using the authors’ language from the paper being curated. 

=== Ancestry Category

* Each detailed descriptor is mapped to an ancestry category and the samples are combined if they belong to the same category. A complete list of ancestry categories used in the Catalog can be found in link:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5815218/table/Tab1/?report=objectonly[Table 1, Morales et al 2018].
* The mappings of detailed descriptions to ancestry categories are carefully considered for each study.  The decision is based on information provided by the author and, where not stated, information provided by peer-reviewed population genetics publications, The World Factbook, the geographical region and additional published resources.  
* If the author reports that ancestry is both "genetically assessed" and "self-reported", the sample ancestry in the Catalog is reported according to the genetically assessed methods.
* Founder populations are assigned the category provided by the author. If no category is given, these are assigned the category “Other”.
* “Asian unspecified” or “African unspecified” is used when curators are not able to assign a more specific ancestry category. For example, “200 Asian individuals recruited in Malaysia, Singapore, and the U.S.” is listed as “Asian unspecified”.
*  “Other” - “other” is assigned if an ancestry descriptor is provided by the author but insufficient information is given to allow curators to assign it to one of the categories, e.g. “Russian”.
* “Other admixed ancestry” – “other admixed ancestry” is selected if the author has stated that the samples are admixed but the admixture is other than the known admixture represented in the categories “African American or Afro-Caribbean” and “Hispanic or Latin American” 
* “Not Reported” - “NR” is assigned if no ancestry is reported in the paper and any country of recruitment provided cannot be used to infer the ancestry. “NR” is also used if the author classifies the samples as “other ancestry” when listing several ancestral categories. 

==== When no ancestry data is provided by authors

* When no ancestry descriptor is used by the author but a country of recruitment is stated, curators use additional published materials to infer the category. This includes relevant ancestry publications and population information provided by link:https://www.cia.gov/library/publications/resources/the-world-factbook/index.html[The World Factbook]. 
* The World Factbook is a reference resource, produced by the U.S. Central Intelligence Agency, which provides information about the demographics, geography, communications, government, economy, and military of countries. This may include information on the ancestry of groups that make up the population of a country. This information is used to infer the ancestry of a study sample when the country of recruitment of the samples is the only information provided. Ancestry is only inferred for countries with > 90% of the same ancestry according to The World Factbook. Ancestry is not assumed for countries with < 90% of the same ancestry; in this case “NR” is entered.
* Other resources are consulted for a number of countries with a high proportion of admixture. For example, scientific papers have been consulted to provide ancestry information on countries in Latin America and the Caribbean.

=== Country of Recruitment 

* Country of recruitment of the sample is extracted if stated by the author. Country of recruitment is not inferred from an ancestry identifier e.g. “100 Thai cases” does not necessarily mean that country of recruitment is “Thailand”.
* Country of recruitment is not assumed from a cohort or Biobank name (e.g. “Twins UK”, “Framingham Heart Study”); the specific location of recruitment of the samples must have been mentioned. An exception to this is if the samples are referred to as being recruited within a National Health Scheme or similar.
* When the descriptor "African American", “European American”, “Mexican American” or “American Indian” is provided, the U.S. is entered as the country of recruitment.
* “NR” is entered when no country of recruitment is provided.

=== Country of Origin

* Country of origin is entered if the author provides details of the country of origin of an individual’s grandparents. 
* Country of origin is also entered if there is evidence of known genealogy associated with a country of origin, e.g. “knowledge of Icelandic genealogy” has been used to justify assigning country of origin.
* “NR” is entered when no country of origin is provided.
* Country of origin information is only included in the link:file-downloads[spreadsheet download].


=== Additional Description

* All ancestry descriptors provided by the author are entered in the “Additional description” under the “Ancestry category” to which they have been mapped (this applies to GWAS Catalog studies from January 2016 onwards).
* When describing admixed samples, if provided by the author, the distinct ancestral backgrounds that contribute to admixture are entered in the “Additional description” under the “Other admixed ancestry” category.


== Full Ancestry Extraction details

For additional information please review our link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/ancestry[GWAS Catalog Ancestry Extraction Guidelines] and our paper, Morales et al., 2018, link:https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1396-2[A standardized framework for representation of ancestry data in genomics studies, with application to the NHGRI-EBI GWAS Catalog]. 


== Finding Curated Ancestry Data

Ancestry-related data are found in the Studies and Associations tables when searching the Catalog. The detailed and controlled descriptions can be found in the Studies table, either by pressing “Expand all Studies” or the “+” on the study of interest. The controlled description follows the format: sample size, category, (country of recruitment). In cases where multiple ancestries are included in a study, the ancestry associated with a particular association is found as an annotation in the p value column in the Associations table. Ancestry data is also available as a download from our download page. For an overview of the kind of data found in this file, refer to link:http://www.ebi.ac.uk/gwas/docs/fileheaders#_file_headers_for_ancestry_download[the file header descriptions.]

== References

The following publications include analysis of the GWAS Catalog ancestry data.

_Morales et al._ +
http://rdcu.be/G6Fv[A standardized framework for representation of ancestry data in genomics studies, with application to the NHGRI-EBI GWAS Catalog] +
Genome Biology (2018) 19:21 +

_Popejoy AB and Fullerton SM._ +
http://www.nature.com/news/genomics-is-failing-on-diversity-1.20759[Genomics is failing on diversity] +
Nature. 2016, 538 (7624), 161-164. +

_Need, AC and Goldstein, DB._ +
http://europepmc.org/abstract/MED/19836853[Next generation disparities in human genomics: concerns and remedies] +
Trends Genet. 2009, 25, 489–494. +

== Other Resources 

link:https://unstats.un.org/unsd/methodology/m49/[The United Nations M49 Standard of Geographic Regions]

link:https://www.cia.gov/library/publications/resources/the-world-factbook/index.html[The World Factbook] 
