= Downloading the GWAS Catalog

== Downloading the GWAS Catalog

The most recent edition of the GWAS Catalog is link:../api/search/downloads/full[available for download here]

For a description of the file's column headings, go to link:fileheaders[this page].


The most recent edition of the GWAS Catalog with added ontology annotations is link:../api/search/downloads/alternative[available for download here]

For a description of the file's additional column headings, go to link:fileheaders#_file_headers_for_catalog_version_1_0_1[this page].


We are working to provide richer, fully customise-able downloads of GWAS data and these will be available soon.

=== Try our new spreadsheet download

#Beta Feature#

As part of ongoing improvements mapping information will be added for all GWAS Catalog SNPs to Ensembl genes, in addition to NCBI genes.

We are in the process of testing and developing this feature and in order to gather feedback the GWAS Catalog with added mapping information is link:../api/search/downloads/ensembl_mapping[available for download here]

We'd love to hear what you think of this new feature, contact the GWAS Catalog team on mailto:gwas-info@ebi.ac.uk[gwas-info@ebi.ac.uk]

////
== Old version of the spreadsheet

As of 15/6/2015, all CNV studies that were included in the GWAS Catalog for historical reasons have been removed as they did not meet the Catalog's eligibility criteria. At the same time, the "CNV?" column in the download spreadsheet, used to flag CNV studies, was removed as it was redundant. A version of the old spreadsheet format, including the removed studies and all other data up to 2/5/2015 is link:../api/search/downloads/old[available for download here]
////

== Citing the GWAS Catalog

Please see the link:about[About] page for citation guidance.

