= Downloading the GWAS Catalog

== Downloading the GWAS Catalog


[width="60%",options="header",cols="2,1,2,1", frame="all", grid="cols", halign = "center"]
|===
|Description | Download Link |Format  | Column header descriptions

|All associations *v1.0*
|link:../api/search/downloads/full[ Click to download]
|tab separated file
|link:fileheaders[ Click to view]


|All associations *v1.0.2 - with added ontology annotations, GWAS Catalog study accession numbers and genotyping technology*
|link:../api/search/downloads/alternative[ Click to download]
|tab separated file
|link:fileheaders#_file_headers_for_catalog_version_1_0_1[ Click to view]


|All studies  *v1.0*
|link:../api/search/downloads/studies[ Click to download]
|tab separated file
|link:fileheaders[ Click to view]


|All studies *v1.0.2 - with added ontology annotations GWAS Catalog study accession numbers and genotyping technology*
|link:../api/search/downloads/studies_alternative[ Click to download]
|tab separated file
|link:fileheaders#_file_headers_for_catalog_version_1_0_1[ Click to view]


|All ancestry data _(link:faq#faq-G1[see FAQ G1 for more details])_
|link:../api/search/downloads/ancestry[ Click to download]
|tab separated file
|link:fileheaders#_file_headers_for_ancestry_download[ Click to view]
|===


File name conventions:

* v1.0 indicates the columns originally proposed by the NCBI
* v1.0.1 indicates the addition of ontology annotations, GWAS Catalog study accession numbers and other new columns (dismissed) 
* v1.0.2 indicates the addition of ontology annotations, GWAS Catalog study accession numbers and other new columns such as genotyping technology
* eXX indicates the Ensembl release version that the data is mapped to
* rYYYY-MM-DD indicates the date on which the GWAS Catalog was released

Older versions of the GWAS Catalog, with or without ontology annotations, can be found on link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases[ our FTP server].

We are working to provide richer, fully customise-able downloads of GWAS data and these will be available soon.



== GWAS to EFO mappings

A file showing all GWAS to EFO mappings, including the parent category each trait is mapped to on the diagram can be found link:../api/search/downloads/trait_mappings[ here] and on link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest[ our FTP server]. Note that mappings are not one-to-one, i.e. one EFO term may be mapped to several different GWAS traits and vice versa.




== Downloading the GWAS Catalog as RDF/OWL

*CAUTION*: Some of these files may be very large - attempting to open them in your browser may take a very long time. It is usually safest to right-click and choose "save as..." to download these files.

Each release of the GWAS Catalog is also available as an link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/gwas-kb.owl[OWL knowledge base] that can be loaded into an RDF triple store. In order to work with the knowledge base, a copy of the link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/gwas-diagram.owl[schema ontology] and of the link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/efo.owl[Experimental Factor Ontology (EFO)] are required. For more information on our use of ontologies, see our link:ontology[ontology] page.


==== _Citing the GWAS Catalog_

_Please see the link:about[About] page for citation guidance._
