= Programmatic access

== Programmatic access

The full REST API for the GWAS Catalog is still under development so please check this page regularly for updates or contact the GWAS Catalog team at gwas-info@ebi.ac.uk. You can however link into the Catalog and build bookmarks using the guide below.



=== Bookmarking your searches

You can bookmark all queries for main search terms, eg http://www.ebi.ac.uk/gwas/search?query=diabetes[diabetes] as well as for individual search facets, eg http://www.ebi.ac.uk/gwas/search?query=diabetes#association[only associations (not studies or traits) for the term diabetes]. It is currently not possible to bookmark filters, so if you are only interested in associations with a certain p-value cut-off or studies published after a certain date, you will still need to reapply these filters every time you return to the search.


=== Bookmarking help documents

You can bookmark any part of the GWAS Catalog page, including individual questions in the FAQ document. Please note that if you use Chrome as your web browser, jumping directly to a question may not always work. This is a browser bug outside our control.


=== Linking into the Catalog

Any concept that can be searched in the Catalog can also be linked to via a structured URL. Below are some examples of common use cases.


==== Base URL

The base URL for any Catalog link is

 search?query=

==== Trait

Example for a trait such as breast cancer

 search?query=breast%20cancer


==== rsID

Example for a SNP rsID such as rs7329174

 search?query=rs7329174

==== Gene name

Example for a gene name such as HBS1L

 search?query=HBS1L


==== Pubmed ID

Example for a Pubmed ID such as 23043469

 search?query=23043469

==== Author

Example for a author name such as Yang

 search?query=Yang

==== Base pair location

Example for a base pair location such as 40983974

 search?query=40983974

==== Cytogenetic location

Example for a cytogenetic location such as 2q37.1

 search?query=2q37.1


==== Ontology ID

Example for an ontology ID such as EFO_0004541

 search?query=EFO_0004541