= Programmatic access

== Programmatic access

The full REST API for the GWAS Catalog is still under development so please check this page regularly for updates or contact the GWAS Catalog team at gwas-info@ebi.ac.uk. You can however link into the Catalog and build bookmarks using the guide below.

=== Bookmarking your searches

You can bookmark all queries for main search terms, eg http://www.ebi.ac.uk/gwas/search?query=diabetes[diabetes] as well as for individual search facets, eg http://www.ebi.ac.uk/gwas/search?query=diabetes#association[only associations (not studies or traits) for the term diabetes]. It is currently not possible to bookmark filters, so if you are only interested in associations with a certain p-value cut-off or studies published after a certain date, you will still need to reapply these filters every time you return to the search.

=== Bookmarking help documents

You can bookmark any part of the GWAS Catalog page, including individual questions in the FAQ document. Please note that if you use Chrome as your web browser, jumping directly to a question may not always work. This is a browser bug outside our control.


