= Related resources

=== GWAS Webinars

On Wednesday, June 28th, 2017, the GWAS Catalog team at EMBL-EBI held http://www.ebi.ac.uk/training/online/course/nhgri-ebi-gwas-catalog-curated-resource-snp-trait-associations[a webinar] to provide a background to genome-wide association study design and introduce users to the GWAS Catalog. Topics such as Catalog content, data availability and access, search capability, and interoperability with other resources were discussed.

On Thursday, July 18th, 2013, the Division of Genomic Medicine held http://www.genome.gov/27554296[a webinar] to highlight current uses and explore  priorities and future directions for the GWAS catalog.


=== GWAS Catalog training materials

==== EBI Train online

The EBI Train online platform provides an easily accessible interactive tutorial to allow users to explore the full range of features the GWAS Catalog has to offer. Check out link:http://www.ebi.ac.uk/training/online/course/gwas-catalog-exploring-snp-trait-associations[ GWAS Catalog - Exploring SNP-trait associations] to find out more.


==== Other training materials

Training materials from workshops held by the GWAS Catalog team are available on link:ftp://ftp.ebi.ac.uk/pub/databases/gwas/training_materials/[ our FTP server]. If you would like to make use of these slides, please cite the GWAS Catalog as detailed on the link:about[About] page.


=== Various resources & projects
http://www.ensembl.org[Ensembl Genome Browser]

//http://www.gen2phen.org/[GEN2PHEN Project]

http://geneticassociationdb.nih.gov/[Genetic Association Database]

http://www.geneticsofgeneexpression.org/network/[Human Gene Coexpression Database]

http://www.hapmap.org/[International HapMap Project]

http://www.phenxtoolkit.org[PhenX Toolkit (consensus measures of Phenotypes and eXposures)]

http://genome.ucsc.edu/cgi-bin/hgGateway[Genome Browser Gateway]


=== HuGE Navigator (Centers for Disease Control and Prevention)
https://phgkb.cdc.gov/HuGENavigator/gWAHitStartPage.do[GWAS Integrator]

https://phgkb.cdc.gov/HuGENavigator/startPagePubLit.do[HuGE Literature Finder]

https://phgkb.cdc.gov/HuGENavigator/startPageMapper.do[Variant Name Mapper]


=== National Center for Biotechnology Information (NCBI) Links
http://www.ncbi.nlm.nih.gov/projects/SNP/[dbSNP]

http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene[Entrez Gene]

http://www.ncbi.nlm.nih.gov/Genbank/[GenBank]

http://www.ncbi.nlm.nih.gov/sites/entrez/[PubMed]

http://www.ncbi.nlm.nih.gov/gap/PheGenIUCSC[Phenotype-Genotype Integrator]


=== GWAS tools & data services
https://bio.tools/?page=1&q=GWAS%20study&sort=score&ord=desc[Elixir Tools and Data Services Registry]
