/*

################################################################################
Add in additional gene data for any genes that were not present in the GWASGENE
table, but which present in the GWASSTUDIESSNP table.

Designed for execution with Flyway database migrations tool.

author:  Tony Burdett
date:    February 6rd 2015
version: 1.9.9.019 (pre 2.0)
################################################################################

*/


--------------------------------------------------------
-- Migrate newly linked gene data into GENOMIC_CONTEXT
--------------------------------------------------------

-- UPSTREAM
INSERT INTO GENOMIC_CONTEXT (SNP_ID, GENE_ID, IS_INTERGENIC, IS_UPSTREAM, IS_DOWNSTREAM, DISTANCE, ENTREZ_GENE_ID)
  SELECT DISTINCT s.ID AS SNP_ID, g.ID AS GENE_ID, 1 AS IS_INTERGENIC, 1 AS IS_UPSTREAM, 0 AS IS_DOWNSTREAM, gs.UPSTREAM_GENE_DISTANCE AS DISTANCE, gs.UPSTREAM_GENE_ID AS ENTREZ_GENE_ID
  FROM GWASSTUDIESSNP gs
  JOIN GWASSNPXREF sx ON sx.GWASSTUDIESSNPID = gs.ID
  JOIN GWASSNP s ON sx.SNPID = s.ID
  JOIN GENE g ON g.GENE_NAME = gs.UPSTREAM_GENE_SYMBOL
  WHERE UPSTREAM_GENE_DISTANCE IS NOT NULL
  AND INTERGENIC = 1
  AND g.ID > '10000000';
-- DOWNSTREAM
INSERT INTO GENOMIC_CONTEXT (SNP_ID, GENE_ID, IS_INTERGENIC, IS_UPSTREAM, IS_DOWNSTREAM, DISTANCE, ENTREZ_GENE_ID)
  SELECT DISTINCT s.ID AS SNP_ID, g.ID AS GENE_ID, 1 AS IS_INTERGENIC, 0 AS IS_UPSTREAM, 1 AS IS_DOWNSTREAM, gs.DOWNSTREAM_GENE_DISTANCE AS DISTANCE, gs.DOWNSTREAM_GENE_ID AS ENTREZ_GENE_ID
  FROM GWASSTUDIESSNP gs
  JOIN GWASSNPXREF sx ON sx.GWASSTUDIESSNPID = gs.ID
  JOIN GWASSNP s ON sx.SNPID = s.ID
  JOIN GENE g ON g.GENE_NAME = gs.DOWNSTREAM_GENE_SYMBOL
  WHERE DOWNSTREAM_GENE_DISTANCE IS NOT NULL
  AND INTERGENIC = 1;
-- INTERGENIC
INSERT INTO GENOMIC_CONTEXT (SNP_ID, GENE_ID, IS_INTERGENIC, IS_UPSTREAM, IS_DOWNSTREAM, DISTANCE, ENTREZ_GENE_ID)
  SELECT DISTINCT s.ID AS SNP_ID, g.ID AS GENE_ID, 0 AS IS_INTERGENIC, 0 AS IS_UPSTREAM, 0 AS IS_DOWNSTREAM, NULL AS DISTANCE, gs.SNP_GENE_IDS AS ENTREZ_GENE_ID
  FROM GWASSTUDIESSNP gs
  JOIN GWASSNPXREF sx ON sx.GWASSTUDIESSNPID = gs.ID
  JOIN GWASSNP s ON sx.SNPID = s.ID
  JOIN GENE g ON g.GENE_NAME = gs.SNP_GENE_SYMBOLS
  WHERE INTERGENIC = 0
  AND g.ID > '10000000';