/*
################################################################################
Migration script to create add an ID column to MONTHLY_CURATOR_TOTALS_SUMMARY_VIEW and
YEARLY_CURATOR_TOTALS_SUMMARY_VIEW

Designed for execution with Flyway database migrations tool; this should be
automatically run to completely generate the schema that is out-of-the-box
compatibile with the GOCI model (see
https://github.com/tburdett/goci/tree/2.x-dev/goci-core/goci-model for more).

author:  Emma Hastings
date:    Oct 02nd 2015
version: 1.9.9.058 (pre 2.0)
################################################################################
*/
--------------------------------------------------------
--  CREATE MONTHLY_CURATOR_TOTALS_SUMMARY_VIEW
--------------------------------------------------------

CREATE OR REPLACE VIEW MONTHLY_TOTALS_SUMMARY_VIEW (ID, YEAR, MONTH, CURATOR, CURATOR_TOTAL, CURATION_STATUS, MONTHLY_TOTAL)
AS SELECT ROWNUM, V.* FROM (SELECT YEAR_E AS YEAR, MONTH_E AS MONTH, CURATOR, CURATOR_TOTAL, CURATION_STATUS, MONTHLY_TOTAL FROM (
(SELECT EXTRACT (YEAR FROM (TRUNC(TO_DATE(S.PUBLICATION_DATE), 'YEAR'))) AS YEAR_E,
EXTRACT (MONTH FROM (TRUNC(TO_DATE(S.PUBLICATION_DATE), 'MONTH'))) AS MONTH_E,
C.LAST_NAME AS CURATOR,
COUNT(C.LAST_NAME) AS CURATOR_TOTAL,
CS.STATUS AS CURATION_STATUS
FROM STUDY S, HOUSEKEEPING H, CURATOR C, CURATION_STATUS CS
WHERE S.HOUSEKEEPING_ID = H.ID
AND H.CURATION_STATUS_ID = CS.ID
AND H.CURATOR_ID = C.ID
GROUP BY TRUNC(TO_DATE(S.PUBLICATION_DATE), 'YEAR'), TRUNC(TO_DATE(S.PUBLICATION_DATE), 'MONTH'),CS.STATUS, C.LAST_NAME
ORDER BY TRUNC(TO_DATE(S.PUBLICATION_DATE), 'YEAR') DESC,TRUNC(TO_DATE(S.PUBLICATION_DATE), 'MONTH') DESC, C.LAST_NAME
) E FULL JOIN (SELECT EXTRACT (YEAR FROM (TRUNC(TO_DATE(PUBLICATION_DATE), 'YEAR'))) AS YEAR_N,
EXTRACT (MONTH FROM (TRUNC(TO_DATE(PUBLICATION_DATE), 'MONTH'))) AS MONTH_N,
COUNT(ID) AS MONTHLY_TOTAL
FROM STUDY
GROUP BY TRUNC(TO_DATE(PUBLICATION_DATE), 'MONTH'), TRUNC(TO_DATE(PUBLICATION_DATE), 'YEAR')
ORDER BY TRUNC(TO_DATE(PUBLICATION_DATE), 'MONTH') DESC) N on YEAR_N = YEAR_E AND MONTH_N = MONTH_E)) V;

--------------------------------------------------------
--  CREATE YEARLY_CURATOR_TOTALS_SUMMARY_VIEW
--------------------------------------------------------

CREATE OR REPLACE VIEW YEARLY_TOTALS_SUMMARY_VIEW (ID, YEAR, CURATOR, TOTAL, CURATION_STATUS)
AS SELECT ROWNUM, V.*  FROM (SELECT EXTRACT (YEAR FROM (TRUNC(TO_DATE(S.PUBLICATION_DATE), 'YEAR'))) AS YEAR,
C.LAST_NAME AS CURATOR,
COUNT(C.LAST_NAME) AS TOTAL,
CS.STATUS AS CURATION_STATUS
FROM STUDY S, HOUSEKEEPING H, CURATOR C, CURATION_STATUS CS
WHERE S.HOUSEKEEPING_ID = H.ID
AND H.CURATION_STATUS_ID = CS.ID
AND H.CURATOR_ID = C.ID
GROUP BY TRUNC(TO_DATE(S.PUBLICATION_DATE), 'YEAR'), CS.STATUS, C.LAST_NAME
ORDER BY TRUNC(TO_DATE(S.PUBLICATION_DATE), 'YEAR') DESC, C.LAST_NAME) V;