/*################################################################################

Migration script to replace Monthly_total_summary_view with new Publication table

author:  C Malangone
date:    March 2018
version: 2.2.0.042
################################################################################
*/

CREATE OR REPLACE VIEW MONTHLY_TOTALS_SUMMARY_VIEW AS
  SELECT ROWNUM AS ID, V."YEAR" AS YEAR,V."MONTH" AS MONTH,V."CURATOR" AS CURATOR,V."CURATOR_TOTAL" AS CURATOR_TOTAL,V."CURATION_STATUS" AS CURATION_STATUS,V."MONTHLY_TOTAL" AS MONTHLY_TOTAL
  FROM (SELECT YEAR_E AS YEAR, MONTH_E AS MONTH, CURATOR AS CURATOR, CURATOR_TOTAL AS CURATOR_TOTAL, CURATION_STATUS AS CURATION_STATUS, MONTHLY_TOTAL AS MONTHLY_TOTAL FROM (
      (SELECT EXTRACT (YEAR FROM (TRUNC(TO_DATE(P.PUBLICATION_DATE), 'YEAR'))) AS YEAR_E,
              EXTRACT (MONTH FROM (TRUNC(TO_DATE(P.PUBLICATION_DATE), 'MONTH'))) AS MONTH_E,
              C.LAST_NAME AS CURATOR,
              COUNT(C.LAST_NAME) AS CURATOR_TOTAL,
              CS.STATUS AS CURATION_STATUS
       FROM STUDY S, PUBLICATION P, HOUSEKEEPING H, CURATOR C, CURATION_STATUS CS
       WHERE S.HOUSEKEEPING_ID = H.ID
             AND S.PUBLICATION_ID = P.ID
             AND H.CURATION_STATUS_ID = CS.ID
             AND H.CURATOR_ID = C.ID
       GROUP BY TRUNC(TO_DATE(P.PUBLICATION_DATE), 'YEAR'), TRUNC(TO_DATE(P.PUBLICATION_DATE), 'MONTH'),CS.STATUS, C.LAST_NAME
       ORDER BY TRUNC(TO_DATE(P.PUBLICATION_DATE), 'YEAR') DESC,TRUNC(TO_DATE(P.PUBLICATION_DATE), 'MONTH') DESC, C.LAST_NAME
      ) E FULL JOIN (SELECT EXTRACT (YEAR FROM (TRUNC(TO_DATE(P.PUBLICATION_DATE), 'YEAR'))) AS YEAR_N,
                            EXTRACT (MONTH FROM (TRUNC(TO_DATE(P.PUBLICATION_DATE), 'MONTH'))) AS MONTH_N,
                            COUNT(S.ID) AS MONTHLY_TOTAL
                     FROM STUDY S JOIN PUBLICATION P ON (S.PUBLICATION_ID = P.ID)
                     GROUP BY TRUNC(TO_DATE(P.PUBLICATION_DATE), 'MONTH'), TRUNC(TO_DATE(P.PUBLICATION_DATE), 'YEAR')
                     ORDER BY TRUNC(TO_DATE(P.PUBLICATION_DATE), 'MONTH') DESC) N on YEAR_N = YEAR_E AND MONTH_N = MONTH_E)) V
