/*

################################################################################
Migration script to link new traits to STUDY
author: Jon Stewart
date:    04 Feb 2020
version: 2.4.0.006
################################################################################
*/

alter table "GWAS"."STUDY_EXTENSION" DROP (BACKGROUND_TRAIT, MAPPED_BACKGROUND_TRAIT);


  CREATE TABLE "GWAS"."STUDY_BACKGROUND_TRAIT"
   (	"DISEASE_TRAIT_ID" NUMBER(19,0),
	"STUDY_ID" NUMBER(19,0) NOT NULL ENABLE,
	 PRIMARY KEY ("STUDY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPOT_DATA"  ENABLE,
	 CONSTRAINT "STUDY_BKG_STUDY_ID_FK" FOREIGN KEY ("STUDY_ID")
	  REFERENCES "GWAS"."STUDY" ("ID") ENABLE,
	 CONSTRAINT "STUDY_BKG_DISEASE_TRAIT_ID_FK" FOREIGN KEY ("DISEASE_TRAIT_ID")
	  REFERENCES "GWAS"."DISEASE_TRAIT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPOT_DATA" ;



  CREATE TABLE "GWAS"."STUDY_BACKGROUND_EFO_TRAIT"
   (	"STUDY_ID" NUMBER(19,0) NOT NULL ENABLE,
	"EFO_TRAIT_ID" NUMBER(19,0) NOT NULL ENABLE,
	 CONSTRAINT "STUDY_BKG_EFO_TRAIT_ID_FK" FOREIGN KEY ("EFO_TRAIT_ID")
	  REFERENCES "GWAS"."EFO_TRAIT" ("ID") ENABLE,
	 CONSTRAINT "STUDY_BKG_EFO_STUDY_ID_FK" FOREIGN KEY ("STUDY_ID")
	  REFERENCES "GWAS"."STUDY" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPOT_DATA" ;
