/*

################################################################################

Add additional unpublished columns

author: Jon Stewart
date:    14 May 2020
version: 2.4.0.019

################################################################################
*/
ALTER TABLE UNPUBLISHED_STUDY
ADD (ARRAY_INFORMATION VARCHAR2(255) );

ALTER TABLE UNPUBLISHED_STUDY
ADD (IMPUTATION NUMBER(1,0) );

ALTER TABLE UNPUBLISHED_STUDY
ADD (VARIANT_COUNT INTEGER );

ALTER TABLE UNPUBLISHED_STUDY
ADD (SAMPLE_DESCRIPTION VARCHAR2(255) );

ALTER TABLE UNPUBLISHED_STUDY
ADD (STUDY_DESCRIPTION VARCHAR2(255) );

ALTER TABLE UNPUBLISHED_STUDY
ADD (EFO_TRAIT VARCHAR2(255) );

ALTER TABLE UNPUBLISHED_STUDY
ADD (BACKGROUND_EFO_TRAIT VARCHAR2(255) );

ALTER TABLE UNPUBLISHED_STUDY
ADD (SUM_STATS_ASSEMBLY VARCHAR2(255) );

ALTER TABLE UNPUBLISHED_STUDY
ADD (COHORT VARCHAR2(255) );

ALTER TABLE UNPUBLISHED_STUDY
ADD (COHORT_ID VARCHAR2(255) );
