/*

################################################################################

Increase column sizes for unpublished tables

author: Jon Stewart
date:    11 June 2020
version: 2.5.0.001

################################################################################
*/
ALTER TABLE BODY_OF_WORK
MODIFY (JOURNAL VARCHAR2(255 BYTE) );

ALTER TABLE BODY_OF_WORK
MODIFY (FIRST_AUTHOR VARCHAR2(255 BYTE) );

ALTER TABLE UNPUBLISHED_STUDY
MODIFY (STUDY_TAG VARCHAR2(255 BYTE) );

ALTER TABLE UNPUBLISHED_STUDY
MODIFY (ARRAY_MANUFACTURER VARCHAR2(255 BYTE) );

ALTER TABLE UNPUBLISHED_ANCESTRY
MODIFY (STUDY_TAG VARCHAR2(255 BYTE) );

ALTER TABLE UNPUBLISHED_ANCESTRY
MODIFY (STUDY_TAG VARCHAR2(255 BYTE) );

ALTER TABLE UNPUBLISHED_ANCESTRY
MODIFY (ANCESTRY_CATEGORY VARCHAR2(255 BYTE) );
