/*
################################################################################
Migration script to change columns in ASSOCIATION_REPORT from VARCHAR2 to CLOB

author: Tudor Groza
date:    9 October 2020
version: 2.6.0.001
################################################################################
*/

  ALTER TABLE "ASSOCIATION_REPORT"
    ADD (TMP_SNP_ERROR  CLOB);

  UPDATE "ASSOCIATION_REPORT" SET TMP_SNP_ERROR=SNP_ERROR;
  COMMIT;

  ALTER TABLE "ASSOCIATION_REPORT" DROP COLUMN SNP_ERROR;

  ALTER TABLE "ASSOCIATION_REPORT"
    RENAME COLUMN TMP_SNP_ERROR TO SNP_ERROR;

--------------------------------------------------------

  ALTER TABLE "ASSOCIATION_REPORT"
    ADD (TMP_SNP_GENE_ON_DIFF_CHR  CLOB);

  UPDATE "ASSOCIATION_REPORT" SET TMP_SNP_GENE_ON_DIFF_CHR=SNP_GENE_ON_DIFF_CHR;
  COMMIT;

  ALTER TABLE "ASSOCIATION_REPORT" DROP COLUMN SNP_GENE_ON_DIFF_CHR;

  ALTER TABLE "ASSOCIATION_REPORT"
    RENAME COLUMN TMP_SNP_GENE_ON_DIFF_CHR TO SNP_GENE_ON_DIFF_CHR;

--------------------------------------------------------

  ALTER TABLE "ASSOCIATION_REPORT"
    ADD (TMP_NO_GENE_FOR_SYMBOL  CLOB);

  UPDATE "ASSOCIATION_REPORT" SET TMP_NO_GENE_FOR_SYMBOL=NO_GENE_FOR_SYMBOL;
  COMMIT;

  ALTER TABLE "ASSOCIATION_REPORT" DROP COLUMN NO_GENE_FOR_SYMBOL;

  ALTER TABLE "ASSOCIATION_REPORT"
    RENAME COLUMN TMP_NO_GENE_FOR_SYMBOL TO NO_GENE_FOR_SYMBOL;

--------------------------------------------------------

  ALTER TABLE "ASSOCIATION_REPORT"
    ADD (TMP_REST_SERVICE_ERROR  CLOB);

  UPDATE "ASSOCIATION_REPORT" SET TMP_REST_SERVICE_ERROR=REST_SERVICE_ERROR;
  COMMIT;

  ALTER TABLE "ASSOCIATION_REPORT" DROP COLUMN REST_SERVICE_ERROR;

  ALTER TABLE "ASSOCIATION_REPORT"
    RENAME COLUMN TMP_REST_SERVICE_ERROR TO REST_SERVICE_ERROR;

--------------------------------------------------------

  ALTER TABLE "ASSOCIATION_REPORT"
    ADD (TMP_SUSPECT_VARIATION_ERROR  CLOB);

  UPDATE "ASSOCIATION_REPORT" SET TMP_SUSPECT_VARIATION_ERROR=SUSPECT_VARIATION_ERROR;
  COMMIT;

  ALTER TABLE "ASSOCIATION_REPORT" DROP COLUMN SUSPECT_VARIATION_ERROR;

  ALTER TABLE "ASSOCIATION_REPORT"
    RENAME COLUMN TMP_SUSPECT_VARIATION_ERROR TO SUSPECT_VARIATION_ERROR;

--------------------------------------------------------

  ALTER TABLE "ASSOCIATION_REPORT"
    ADD (TMP_GENE_ERROR  CLOB);

  UPDATE "ASSOCIATION_REPORT" SET TMP_GENE_ERROR=GENE_ERROR;
  COMMIT;

  ALTER TABLE "ASSOCIATION_REPORT" DROP COLUMN GENE_ERROR;

  ALTER TABLE "ASSOCIATION_REPORT"
    RENAME COLUMN TMP_GENE_ERROR TO GENE_ERROR;
