/*
################################################################################
Migration script to change columns in WEEKLY_REPORT from VARCHAR2 to CLOB

author: Tudor Groza
date:    26 October 2020
version: 2.6.0.005
################################################################################
*/

  ALTER TABLE "WEEKLY_REPORT"
    ADD (TMP_STUDIES_CREATED  CLOB);

  UPDATE "WEEKLY_REPORT" SET TMP_STUDIES_CREATED=STUDIES_CREATED;
  COMMIT;

  ALTER TABLE "WEEKLY_REPORT" DROP COLUMN STUDIES_CREATED;

  ALTER TABLE "WEEKLY_REPORT"
    RENAME COLUMN TMP_STUDIES_CREATED TO STUDIES_CREATED;

--------------------------------------------------------

  ALTER TABLE "WEEKLY_REPORT"
    ADD (TMP_STUDIES_LEVEL1  CLOB);

  UPDATE "WEEKLY_REPORT" SET TMP_STUDIES_LEVEL1=STUDIES_LEVEL1;
  COMMIT;

  ALTER TABLE "WEEKLY_REPORT" DROP COLUMN STUDIES_LEVEL1;

  ALTER TABLE "WEEKLY_REPORT"
    RENAME COLUMN TMP_STUDIES_LEVEL1 TO STUDIES_LEVEL1;

--------------------------------------------------------

  ALTER TABLE "WEEKLY_REPORT"
    ADD (TMP_STUDIES_LEVEL2  CLOB);

  UPDATE "WEEKLY_REPORT" SET TMP_STUDIES_LEVEL2=STUDIES_LEVEL2;
  COMMIT;

  ALTER TABLE "WEEKLY_REPORT" DROP COLUMN STUDIES_LEVEL2;

  ALTER TABLE "WEEKLY_REPORT"
    RENAME COLUMN TMP_STUDIES_LEVEL2 TO STUDIES_LEVEL2;

--------------------------------------------------------

  ALTER TABLE "WEEKLY_REPORT"
    ADD (TMP_STUDIES_PUBLISHED  CLOB);

  UPDATE "WEEKLY_REPORT" SET TMP_STUDIES_PUBLISHED=STUDIES_PUBLISHED;
  COMMIT;

  ALTER TABLE "WEEKLY_REPORT" DROP COLUMN STUDIES_PUBLISHED;

  ALTER TABLE "WEEKLY_REPORT"
    RENAME COLUMN TMP_STUDIES_PUBLISHED TO STUDIES_PUBLISHED;

--------------------------------------------------------

  ALTER TABLE "WEEKLY_REPORT"
    ADD (TMP_PUBS_CREATED  CLOB);

  UPDATE "WEEKLY_REPORT" SET TMP_PUBS_CREATED=PUBS_CREATED;
  COMMIT;

  ALTER TABLE "WEEKLY_REPORT" DROP COLUMN PUBS_CREATED;

  ALTER TABLE "WEEKLY_REPORT"
    RENAME COLUMN TMP_PUBS_CREATED TO PUBS_CREATED;

--------------------------------------------------------

  ALTER TABLE "WEEKLY_REPORT"
    ADD (TMP_PUBS_LEVEL1 CLOB);

  UPDATE "WEEKLY_REPORT" SET TMP_PUBS_LEVEL1=PUBS_LEVEL1;
  COMMIT;

  ALTER TABLE "WEEKLY_REPORT" DROP COLUMN PUBS_LEVEL1;

  ALTER TABLE "WEEKLY_REPORT"
    RENAME COLUMN TMP_PUBS_LEVEL1 TO PUBS_LEVEL1;

--------------------------------------------------------

  ALTER TABLE "WEEKLY_REPORT"
    ADD (TMP_PUBS_LEVEL2  CLOB);

  UPDATE "WEEKLY_REPORT" SET TMP_PUBS_LEVEL2=PUBS_LEVEL2;
  COMMIT;

  ALTER TABLE "WEEKLY_REPORT" DROP COLUMN PUBS_LEVEL2;

  ALTER TABLE "WEEKLY_REPORT"
    RENAME COLUMN TMP_PUBS_LEVEL2 TO PUBS_LEVEL2;

--------------------------------------------------------

  ALTER TABLE "WEEKLY_REPORT"
    ADD (TMP_PUBS_PUBLISHED  CLOB);

  UPDATE "WEEKLY_REPORT" SET TMP_PUBS_PUBLISHED=PUBS_PUBLISHED;
  COMMIT;

  ALTER TABLE "WEEKLY_REPORT" DROP COLUMN PUBS_PUBLISHED;

  ALTER TABLE "WEEKLY_REPORT"
    RENAME COLUMN TMP_PUBS_PUBLISHED TO PUBS_PUBLISHED;

--------------------------------------------------------
